Fix misc http issues
AzureAD/microsoft-authentication-library-common-for-android pull request #1040
Opened 2020-09-17 12:14 UTC by kkrishnareddy

1. remove null key headers from response.
2. no post request if the content length is zero.

2020-09-17 15:11 UTC, AdamBJohnsonx commented on common/src/main/java/com/microsoft/identity/common/internal/net/HttpResponse.java
> +    return filteredHeaders;
Why are we doing this in MSAL common?  This seems to be a problem specific to the C++ applications, and should be fixed in the adapter layer there.

2020-09-19 02:40 UTC, dabbcomputers requested changes
> 1. remove null key headers from response.
> 2. no post request if the content length is zero.

Don't complete the CR before getting approval from Shane. He wants to have  discussion with Adam first.

2020-09-21 17:42 UTC, AdamBJohnsonx commented on common/src/main/java/com/microsoft/identity/common/internal/net/HttpResponse.java
> +    return filteredHeaders;
Thing is, this is actually fixed in MSAL-Cpp now.  So I'm not sure we need to do this here.  If we were going to take on moving this to a new field, I'd create one in HttpResponse called mStatusLine and put it there.  The question is - do we need to do this at all?

2020-09-29 21:30 UTC, AdamBJohnsonx commented on common/src/main/java/com/microsoft/identity/common/internal/net/HttpResponse.java
> +        mResponseHeaders = filterNullKeyHeaders(responseHeaders);
```suggestion
        mResponseHeaders = responseHeaders;
```

2020-09-29 21:31 UTC, AdamBJohnsonx commented on common/src/main/java/com/microsoft/identity/common/internal/net/HttpResponse.java
> +        mResponseHeaders = filterNullKeyHeaders(headerFields);
```suggestion
        mResponseHeaders = headerFields;
```

2020-09-29 21:32 UTC, AdamBJohnsonx commented on common/src/main/java/com/microsoft/identity/common/internal/net/HttpResponse.java
> +    return filteredHeaders;
```suggestion
```

2020-09-29 21:40 UTC, iambmelt requested changes
I don't think we want this change; as @AdamBJohnsonx states this looks be
1. The wrong repo for this code
2. Already being done in MSAL CPP

As a small aside, the code style isn't consistent with this repo.

Our braces are
```java
void braces() {
    // like this
}
```

and

```java
void braces() 
{
    // Not like this
}
```

And we use `final` wherever possible

2021-02-22 23:02 UTC, iambmelt commented
Closing due to inactivity

2021-02-22 23:02 UTC, closed without merging