Add constants in Common
AzureAD/microsoft-authentication-library-common-for-android pull request #1686
Opened 2022-03-03 01:10 UTC by tanmaymanolkar1

Support change fir
AzureAD/ad-accounts-for-android#1812

2022-03-08 17:11 UTC, shoatman approved these changes
lgtm

2022-03-08 17:31 UTC, rpdome commented on common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
> +        public static final String METHOD_COMPANY_PORTAL =
nit: let's rename the var to be more specific.

2022-03-08 17:31 UTC, rpdome approved these changes

2022-03-14 20:49 UTC, iamgusain commented on common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
> +        public static final String METHOD_COMPANY_PORTAL =
COMPANY_PORTAL_CONTENT_PROVIDER_METHOD_ON_GLOBAL_SIGNOUT

2022-03-14 20:51 UTC, iamgusain requested changes

2022-03-14 20:51 UTC, iamgusain commented on common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
> +        public static final String AUTHORITY_COMPANY_PORTAL =
COMPANY_PORTAL_CONTENT_PROVIDER_AUTHORITY

2022-03-14 20:51 UTC, iamgusain commented on common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
> +        public static final String AUTHORITY_COMPANY_PORTAL =
nit: I think these two constants should go into separate class.. CompanyPortalContentProviderCall

2022-03-22 19:54 UTC, closed without merging