Enable signing testFixtureJar for maven publication
AzureAD/microsoft-authentication-library-common-for-android pull request #1880
Opened 2022-10-24 22:14 UTC by iamgusain

Enabling the support for signing testfixture jar when creating maven package for publishing.
Currently it's not signed, and it fails verification when releasing to external maven with error "Missing Signature" for the testfixture jar

2022-10-25 02:29 UTC, p3dr0rv requested changes

2022-10-25 02:29 UTC, p3dr0rv commented on azure-pipelines/maven-release/common4j.yml
> +    testFixtureJar: true
```suggestion
    gpgTestFixtureJar: true
```

2022-10-25 02:29 UTC, p3dr0rv commented on azure-pipelines/templates/steps/maven-release/gpg-signing.sh
> +if [ $TESTFIXUTREJAR == "true" ]; then
```suggestion
if [ $TESTFIXTUREJAR == "true" ]; then
```

2022-10-25 02:58 UTC, shahzaibj commented
It seems like the bigger issue here is that testFixtures are being released to external maven? Should we try to fix that rather than signing these?

2022-10-27 21:11 UTC, iamgusain commented
> It seems like the bigger issue here is that testFixtures are being released to external maven? Should we try to fix that rather than signing these?

testFixture jar is by default generated by the testFixture plugin, in our maven release we are copying all the generated jars as part of the maven package. We can exclude it there but I thought we included these as testFixture so the consumers could use them for testing. If these are internal only, should these be part of our other testUtil libs.

2022-11-07 23:56 UTC, shahzaibj commented
> > It seems like the bigger issue here is that testFixtures are being released to external maven? Should we try to fix that rather than signing these?
> 
> testFixture jar is by default generated by the testFixture plugin, in our maven release we are copying all the generated jars as part of the maven package. We can exclude it there but I thought we included these as testFixture so the consumers could use them for testing. If these are internal only, should these be part of our other testUtil libs.

Interesting question. @p3dr0rv Any thoughts here?

2022-11-08 01:42 UTC, somalaya approved these changes

2023-09-22 14:53 UTC, closed without merging