Update CODEOWNERS
AzureAD/microsoft-authentication-library-common-for-android pull request #2251
Opened 2023-12-07 12:22 UTC by SammyO

With CIAM native auth being merged into dev, set NativeAuthTeam as the owners for the respective files (as agreed with Shahzaib, Fadi and Moumita).

2023-12-07 13:24 UTC, rmccahill approved these changes

2023-12-07 15:44 UTC, Yuki-YuXin approved these changes

2023-12-07 16:13 UTC, fadidurah commented on CODEOWNERS
> +/common4j/src/testFixtures/java/com/microsoft/identity/internal/ @AzureAD/NativeAuthTeam
Is this correct?

2023-12-07 16:14 UTC, fadidurah commented on CODEOWNERS
> +/common4j/src/testFixtures/java/com/microsoft/identity/internal/ @AzureAD/NativeAuthTeam
Particularly the test fixture addition

2023-12-07 16:35 UTC, SaurabhMSFT commented on CODEOWNERS
> +/common4j/src/testFixtures/java/com/microsoft/identity/internal/ @AzureAD/NativeAuthTeam
yes, we are adding some classes in common4j/testfixtures. These test classes are used by tests in multiple projects.

2023-12-08 15:09 UTC, fadidurah approved these changes

2023-12-08 20:59 UTC, shahzaibj requested changes
Blocking merge for this until @SaurabhMSFT has moved all native auth code to its own package. That way the codeonwers file can target specific package (as opposed to targeting so many different files)

2023-12-12 17:46 UTC, shahzaibj approved these changes

2023-12-13 11:01 UTC, merged